name: new workflow 
on:
  push:
    branches: [ main ]

jobs:
  new_job:
    runs-on: ubuntu-latest
    
    steps:
    - name: print msg
      run: echo" hi i am lachman das"
      
    
    
    
  
